libfmt assert needs /utf-8 for unicode support
This fixes the following failure:
C:\Tools\vcpkg\installed\x64-windows\include\fmt\base.h(458,28): error C2338: static_assert failed: 'Unicode support requires compiling with /utf-8' [C:\projects\c47edit\c47edit.vcxproj]